### ISSUE TITLE
Fetch logic is broken

### ISSUE THREAD

**Issue by ghost** [get-net/data-mapper#23]
One of the latest [commits](https://github.com/get-net/data-mapper/commit/d739e44a231c3c1bbe1cce1fdfdca6894a97e058) broke the logic of the fetch option for the entity.

I am calling
```lua
section_detailtype:select()
```

Expected:
```yaml
...
- section: a9a01537-ce7c-11eb-b485-bb7b8455eff6
    detailtype:
      name: _7q88crri8
      uid: a9a01539-ce7c-11eb-b485-bb6401c097a9
      formtype: ncform
      data: '{"id": "_1hkvmufab", "ui": {"legend": "тест"}, "name": "тест", "type":
        "object", "properties": {}}'
    uid: a9a0153a-ce7c-11eb-b485-ef35c27e8336
    ordr: 2
...
```
Actual:
```yaml
...
- section: a9a01537-ce7c-11eb-b485-bb7b8455eff6
    detailtype: a9a01539-ce7c-11eb-b485-bb6401c097a9
    uid: a9a0153a-ce7c-11eb-b485-ef35c27e8336
    ordr: 2
...
```
